import fs from 'node:fs';
import crypto from 'node:crypto';
import units from '../authoring/units.mjs';
import {examUrl,official2027,examSlides} from '../authoring/exam2027.mjs';
const old=JSON.parse(fs.readFileSync('authoring/source-course.json','utf8'));
const version='pisid4-2027-template02-v2';
const c={schemaVersion:1,contentVersion:version,id:'pisid4',code:'МДК.05.01',discipline:'Проектирование и дизайн информационных систем',year:'2026–2027',heroTitle:'От документов заказчика',heroAccent:'к проектному решению',slogan:'4 курс · Анализируем, моделируем, объясняем решения.',mascot:'brand/rhino-designer.webp',mascotAlt:'Носорог-проектировщик с материалами информационной системы',logo:'brand/brand-mark.png',ornament:'brand/side-ornament.webp',font:'fonts/raleway-cyrillic.woff2',topicArrow:'brand/topic-arrow.webp',materialsUrl:old.materialsUrl,demo:false,semesters:[7],assessment:{mode:'autonomous',url:'assessment.json'},literature:{primary:[],additional:[]},glossary:[],curriculum:[],lectures:[]};
// Существующие библиографические описания сохраняются, без догадок об ISBN.
const sources=fs.readFileSync('SOURCES.md','utf8').replace('ISBN 978-5-93026-166-10','ISBN в исходном описании требует уточнения');
let reading='';for(const line of sources.split('\n')){if(line.startsWith('## Основная'))reading='primary';else if(line.startsWith('## Дополнительная'))reading='additional';else if(line.startsWith('## '))reading='';if(reading&&line.startsWith('- ')){const url=line.match(/\]\((https[^)]+)\)/)?.[1];c.literature[reading].push({citation:line.slice(2).replace(/\*/g,'').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').trim(),...(url?{url}:{})});}}
const bank={schemaVersion:1,courseId:c.id,contentVersion:version,mode:'autonomous-educational',notice:'Учебная автономная самопроверка: ключи технически доступны посетителям.',keys:{}};
const teacher={schemaVersion:1,courseId:c.id,contentVersion:version,notes:{}};
const registry=[],mapping=[],questionMap=[];
const digest=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const prior=fs.existsSync('private/teacher-source.json')?JSON.parse(fs.readFileSync('private/teacher-source.json','utf8')):null;
const teacherSource={courseId:c.id,contentVersion:version,slides:{}};
const withTeacher=process.argv.includes('--teacher');
function visualText(v){if(!v)return '';if(v.items)return v.items.map(x=>`${x.title}: ${x.text}`).join(' ');if(v.rows)return v.rows.map(x=>x.join(' — ')).join('. ');if(v.type==='cause')return `Причина: ${v.cause}. Следствие: ${v.effect}. Исправление: ${v.solution}.`;return '';}
for(const [li,t] of old.topics.entries()){
 const l={id:t.id,title:t.title,sourceTitle:li<2?'Задание ДЭ 2027 №1 · ER-диаграмма':li===4?'Задания ДЭ 2027 №5–6 · API и документация':'Задание ДЭ 2027 №4 · Информационная система',semester:t.semester,question:t.shortTitle,slides:[]};
 const add=(suffix,s,context={})=>{
  s={id:`${t.id}-${suffix}`,...s};l.slides.push(s);
  if(withTeacher){
   const text=[s.body, ...(s.bullets||[]),s.notebook,visualText(s.visual)].filter(Boolean).join(' ');
   const q=context.unit?.qa.map(([q,a])=>`Вопрос: ${q} Ответ: ${a}`).join('\n')||'';
   const explanation=context.explanation||context.unit?.detail.join(' ')||t.description;
   const answers=s.task?bank.keys[s.task.id]:null;
   const script=s.task?`Сейчас проверяем применение материала вопроса «${context.unit.title}». ${s.task.prompt} Сначала каждый формулирует ответ самостоятельно. ${answers.explanation} ${Object.entries(answers.optionExplanations||{}).map(([id,why])=>`${s.task.options.find(o=>o.id===id)?.text}: ${why}`).join(' ')} После попытки сопоставим обоснование с объяснённым примером, затем продолжим тему.`:
    `${context.opening||`Продолжаем разбор темы «${t.shortTitle}».`} ${text} ${explanation} ${context.unit?`В нашем примере итог следующий: ${context.unit.result}`:''} ${context.transition||'На следующем шаге свяжем это наблюдение с дальнейшим решением.'}`;
   const note={script,preparation:`${context.preparation||'Пример Field Service авторский; идентификаторы и числа условные.'} ${context.unit?.input||t.caseContext} ${li===4?'Комплект КИМ 2027 предоставлен преподавателем; вид аттестации и статусы двух других ГОСТ ещё требуют подтверждения.':''}`,notebook:s.notebook?`Предложить записать после разбора: ${s.notebook}`:context.notebook||'Отдельная запись не требуется; используем конспект текущего вопроса.',questions:q,answer:answers?JSON.stringify(answers,null,2):context.answer||'',estimatedSeconds:s.task?({single:65,multiple:85,short:60,matching:100}[s.task.type]):s.kind==='section'?25:s.kind==='title'?35:s.kind==='literature'?35:s.kind==='materials'?20:s.kind==='notebook'?95:s.visual?100:s.kind==='example'?110:75};
   if(prior?.slides[s.id]){const p=prior.slides[s.id];if(p.contentHash!==digest(s))throw Error(`Изменён слайд ${s.id}: сначала согласуйте заметку в private/teacher-source.json`);teacher.notes[s.id]=p.note;}else teacher.notes[s.id]=note;
   teacherSource.slides[s.id]={contentHash:digest(s),note:teacher.notes[s.id]};
  }
  return s.id;
 };
 add('start',{kind:'title',title:t.shortTitle,kicker:'Лекция '+(li+1)+' · 4 курс',body:t.description},{opening:`Сегодня разбираем: ${t.title}.`,explanation:`К завершению темы требуется ${t.objective}. Результат нашей работы — ${t.deliverable}. Мы пройдём четыре вопроса, в каждом сначала разберём понятия и пример, затем выполним самопроверку. ${t.caseContext}`,transition:'Начнём с источников, на которые опирается подготовка.'});
 for(const group of ['primary','additional'])add(group==='primary'?'main-literature':'additional-literature',{kind:'literature',title:group==='primary'?'Основная литература':'Дополнительная литература',kicker:'Источники',readingGroup:group},{explanation:group==='primary'?'Основные издания из исходного курса дают общий контекст проектирования информационных систем. Библиографические сведения сохранены; номера страниц для этой темы не предоставлены, поэтому привязка к конкретной странице не заявляется.':'Дополнительные издания используются для сопоставления подходов и самостоятельного углубления. Их наличие в списке не означает, что все определения лекции являются дословными цитатами. Для конкретных технических вопросов в конце темы приведены первичные веб-источники.',transition:'Перейдём к доступным материалам занятия.'});
 add('materials',{kind:'materials',title:'Материалы к занятиям',kicker:'Папка курса'},{explanation:'Откройте общую папку по ссылке или QR-коду. Адрес сохранён из исходного проекта. Основное объяснение доступно в самой лекции; содержимое внешней папки не требуется для ответа на обязательные тесты и не входит автоматически в офлайн-копию.',transition:'Теперь посмотрим последовательность учебных вопросов.'});
 add('route',{kind:'agenda',title:'Вопросы темы',kicker:'Карта темы'},{explanation:units.slice(li*4,li*4+4).map((u,i)=>`${i+1}. ${u.title}: ${u.result}`).join(' '),transition:'Начнём с профессиональной задачи и исходных знаний.'});
 add('why',{kind:'theory',title:'Что получится в конце',kicker:'Результат',body:t.objective,bullets:[t.deliverable,'Обоснование решений по исходным данным','Проверка ограничений и отрицательных случаев']},{explanation:`Качество результата определяется не только наличием файла. Для темы «${t.shortTitle}» нужно уметь объяснить связи: ${t.concepts.slice(0,3).map(x=>x.name).join(', ')}. Назовём источник каждого спорного решения и границы уверенности.`});
 add('case',{kind:'example',title:'Field Service: учебный контекст',kicker:'Вводная ситуация',body:t.caseContext},{explanation:`${t.description} Это авторский учебный кейс, а не реальная производственная статистика. Мы будем изменять конкретные условия, чтобы проверить решение. Ответы не требуют знания внешнего проекта.`});
 add('entry',{kind:'theory',title:'На что опираемся',kicker:'Исходные знания',body:li===0?'Документ описывает часть работы организации. Отделяем сообщённое сведение от собственного вывода. Неизвестное сохраняем как вопрос.':'Используем введённую ранее связь: исходный факт → решение → проверяемый результат. Если факта не хватает, явно записываем допущение.',bullets:['Сокращения раскрываются при первом использовании.','Все обязательные тесты опираются на предшествующие слайды.','Часы РПД не предоставлены; маршрут занятия требует согласования.']},{explanation:'Число слайдов не задаёт продолжительность занятия. В сценарии приведена оценка отдельных действий, но она не является утверждённым расписанием. При необходимости материал можно разделить на несколько встреч с сохранением порядка объяснений.'});
 const official=official2027[li];
 add('kod-context',{kind:'theory',title:official[0],kicker:'Подтверждённый первоисточник',body:official[1],source:official[2]},{opening:'Отделим условия официального образца от авторского учебного кейса.',explanation:`${official[1]} Источник проверен 12 сентября 2026 года. Комплект 2027 года предоставлен преподавателем. Вид аттестации, РПД и вариативная часть группы пока не указаны; образец не заменяет выданное экзаменационное задание.`,preparation:official[2],transition:'Дальнейшие примеры относятся к Field Service; при различии условий это оговаривается явно.'});
 for(let qi=0;qi<4;qi++){
  const u=units[li*4+qi],pair=t.concepts.slice(qi*2,qi*2+2),prefix=`Q${String(qi+1).padStart(2,'0')}`,start=l.slides.length;
  add(prefix,{kind:'section',title:u.title,kicker:`Вопрос ${qi+1}`,body:`${pair[0].name} → ${pair[1].name}`},{unit:u,opening:`Переходим к вопросу «${u.title}».`,explanation:`Нужно понять связь двух понятий: ${pair[0].name} и ${pair[1].name}. ${u.input}`,transition:'Сначала уточним значения терминов, затем разберём решение.'});
  for(const [j,concept] of pair.entries()){
   const n=qi*2+j+1;
   let principle=concept.principle;
   if(li===1&&n===3)principle='Внешний ключ (FK) ограничивает ссылку на первичный или иной допустимый уникальный ключ родительской таблицы.';
   if(li===1&&n===2)principle='Первичный ключ (PK) — выбранный уникальный непустой идентификатор строки; стабильность важна для проектирования связей.';
   if(li===1&&n===8)principle='Ссылочная целостность запрещает недопустимые ссылки. Сохранность истории зависит также от выбранной политики удаления.';
   if(li===4&&n===1)principle='Перед включением нормативной ссылки проверяют точное название, статус и область применения в официальном источнике.';
   const context={unit:u,explanation:u.detail[j],transition:j===0?`Теперь рассмотрим, как это связано с понятием «${pair[1].name}».`:'После примера сведём оба понятия в общий результат.'};
   const definition=add(`c${n}-definition`,{kind:'theory',title:concept.name,kicker:'Понятие',body:principle,bullets:[u.detail[j]]},context);
   add(`c${n}-mechanism`,{kind:'process',title:j===0?'Как строится решение':'Как проверяется решение',kicker:concept.name,visual:{type:'process',items:u.steps.slice(j*2,j*2+2).map(([title,text])=>({title,text})),caption:j===0?u.steps[1][1]:u.result}},context);
   add(`c${n}-case`,{kind:'example',title:concept.name+': применение',kicker:'Учебный пример',body:li===4&&n===1?'Старая методичка не подтверждает статус стандарта. Нужно проверить карточку документа.':concept.example,bullets:[concept.decision,`Проверяем: ${concept.check}`]},context);
   add(`c${n}-decision`,{kind:'comparison',title:'Сравним последствия выбора',kicker:concept.name,visual:{type:'comparison',columns:['Решение','Что проверять'],rows:[[concept.decision,concept.check],[concept.pitfall,'Не подтверждает требуемое условие']],caption:u.steps[j*2+1][1]}},context);
   add(`c${n}-mistake`,{kind:'warning',title:'Где решение даёт сбой',kicker:concept.name,body:concept.pitfall,visual:{type:'cause',cause:concept.pitfall,effect:li===1?'Модель не сохраняет смысл фактов и допустимых связей.':li===2?'Пользователь не может надёжно завершить и восстановить сценарий.':li===3?'Действие нарушает границы полномочий или доступность.':li===4?'Документ не позволяет воспроизвести и проверить поведение.':'Вывод перестаёт быть проверяемым по исходным данным.',solution:concept.decision,caption:concept.check}},context);
   add(`c${n}-notebook`,{kind:'notebook',title:'Запишите: '+concept.name,kicker:'Конспект',notebook:`${principle} Проверка: ${concept.check}`},{...context,explanation:`Запись связывает смысл понятия с критерием. ${u.detail[j]}`,transition:'Используем эту формулировку для объяснения следующего примера.'});
   c.glossary.push({term:concept.name,definition:principle,slideIds:[definition]});
  }
  const termsId=add(prefix+'-terms',{kind:'theory',title:'Четыре опорных термина',kicker:'Словарь вопроса',bullets:u.terms.map(([a,b])=>`${a} — ${b}.`)},{unit:u,explanation:'Эти четыре значения различаются по функции в текущем вопросе. '+u.steps.map(([a,b])=>`${a}: ${b}`).join(' '),transition:'Соберём решение целиком и затем выполним четыре задания.'});
  for(const [term,definition]of u.terms)c.glossary.push({term,definition,slideIds:[termsId]});
  add(prefix+'-worked',{kind:'example',title:'Полный разбор решения',kicker:'Учебные данные',body:u.input,visual:{type:'process',items:u.steps.map(([title,text])=>({title,text})),caption:u.result}},{unit:u,opening:'Теперь пройдём весь пример от входных данных до проверенного результата.',explanation:u.steps.map(([a,b])=>`${a}. ${b}`).join(' '),transition:'Вся теория для самопроверки уже введена. Ответьте самостоятельно, затем сравните обоснование.'});
  if(li===4)for(const extra of examSlides.filter(x=>x.question===qi)){const {question:_question,id,explanation,...slide}=extra;add(prefix+'-'+id,{kicker:'ДЭ 2027 · API',...slide},{opening:'Применим способ разбора к приложению ДЭ 2027.',explanation,preparation:'Открыть комплект КИМ 09.02.07-5-2027: приложения 2 и 3. Значения учебного примера условные.',transition:'Сверим контракт с результатом и продолжим текущий вопрос.'});}
  const evidence=l.slides.slice(start).filter(s=>s.kind!=='section').map(s=>s.id),taskIds=[];
  const rotation=(li+qi)%4;
  const order=[0,1,2,3].map(x=>(x+rotation)%4);
  const make=(tn,type,prompt,options,extra,key)=>{const taskId=`L${String(li+1).padStart(3,'0')}-${prefix}-T0${tn}`;const task={id:taskId,type,prompt,...(options?{options}:{}),...extra};bank.keys[taskId]=key;taskIds.push(taskId);add(`${prefix}-T0${tn}`,{kind:'test',title:['Один ответ','Несколько ответов','Краткий ответ','Соответствие'][tn-1],kicker:`Самопроверка · ${tn}/4`,task},{unit:u});};
  const opts=order.map(k=>({id:'o'+k,text:u.terms[k][0]}));
  make(1,'single',`Какой термин обозначает: «${u.terms[0][1]}»? Выберите один ответ.`,opts,{}, {type:'single',correct:['o0'],explanation:`${u.terms[0][0]}: ${u.terms[0][1]}.`,optionExplanations:Object.fromEntries(u.terms.map(([a,b],k)=>['o'+k,k===0?`Верно: ${b}.`:`${a} означает другое: ${b}.`]))});
  const statements=[`${u.terms[0][0]}: ${u.terms[0][1]}.`,`${u.terms[1][0]}: ${u.terms[1][1]}.`,`${u.terms[2][0]}: ${u.terms[3][1]}.`,`${u.terms[3][0]}: ${u.terms[2][1]}.`,`${u.terms[0][0]}: ${u.terms[1][1]}.`];
  const multiOrder=[0,1,2,3,4].map(x=>(x+li+qi)%5);
  make(2,'multiple','Выберите ровно два корректных соответствия термина и значения.',multiOrder.map(k=>({id:'m'+k,text:statements[k]})),{choose:2},{type:'multiple',correct:['m0','m1'],explanation:'Два первых по смыслу термина должны сохранять свои определения; похожие функции не взаимозаменяемы.',optionExplanations:{m0:`Верно: ${u.terms[0][1]}.`,m1:`Верно: ${u.terms[1][1]}.`,m2:`Неверно: это определение термина «${u.terms[3][0]}».`,m3:`Неверно: это определение термина «${u.terms[2][0]}».`,m4:`Неверно: это определение термина «${u.terms[1][0]}».`}});
  make(3,'short',`Введите термин из словаря вопроса: «${u.terms[2][1]}». Только термин, без пояснения.`,null,{}, {type:'short',accepted:[u.terms[2][0]],explanation:`Ответ: ${u.terms[2][0]}. Регистр и повторные пробелы не влияют на проверку; используется термин из словаря вопроса.`});
  make(4,'matching','Сопоставьте четыре термина с их значениями. Каждое значение используется один раз.',[2,0,3,1].map(k=>({id:'r'+k,text:u.terms[k][1]})),{items:u.terms.map(([text],k)=>({id:'i'+k,text}))},{type:'matching',pairs:Object.fromEntries(u.terms.map((_,k)=>['i'+k,'r'+k])),explanation:u.terms.map(([a,b])=>`${a} — ${b}.`).join(' ')});
  questionMap.push({lectureId:l.id,questionId:`L${li+1}-${prefix}`,title:u.title,sourceConcepts:pair.map(x=>x.name),slideIds:l.slides.slice(start).map(s=>s.id),taskIds,evidence,source:'authoring/source-course.json; authoring/units.mjs',outcome:u.result,officialHours:null});
  c.curriculum.push({topic:u.title,outcome:u.result,source:'Авторская группировка исходного курса; соответствие РПД не подтверждено.',slideIds:evidence,taskIds});
 }
 add('summary',{kind:'summary',title:'Связи и выводы темы',kicker:'Итоги',bullets:units.slice(li*4,li*4+4).map(u=>u.result)},{explanation:`Мы получили ${t.deliverable}. ${t.objective}. Качество проверяется на позитивном и отрицательном случае; неопределённые условия остаются явно обозначенными.`,transition:'Для углубления используйте первичные источники.'});
 add('sources',{kind:'literature',title:'Предметные источники',kicker:'Библиография',references:[{citation:'КИМ 09.02.07-5-2027, том 1 и приложения · комплект преподавателя',url:examUrl},...t.sources.filter(s=>!s.url.includes('117431')).slice(0,2).map(s=>({citation:s.label,url:s.url}))]},{explanation:'Основной экзаменационный источник заменён предоставленным комплектом 2027 года. Остальные ссылки унаследованы из курса. Доступность адреса и подтверждение конкретного положения — разные проверки. Статус нормативных документов и актуальный регламент экзамена не объявляются подтверждёнными, если официальная карточка недоступна.',transition:'Проверим готовность результата к передаче.'});
 add('final',{kind:'summary',title:'Перед применением в своём проекте',kicker:'Самостоятельная работа',bullets:[`Соберите: ${t.deliverable}.`,'Назовите источник решения и отдельное допущение.','Покажите один успешный и один отрицательный пример.','Откройте экспортированный файл и проверьте читаемость.']},{explanation:'В самостоятельном проекте условия могут отличаться от Field Service. Переносится способ рассуждения, а не готовые идентификаторы, пороги или кардинальности. Отдельно проверьте те допущения, на которых держится решение.',transition:'Завершим вопросами аудитории.'});
 add('questions',{kind:'questions',title:'Вопросы от аудитории',kicker:'Обсуждение',bullets:['Какое решение изменится при других исходных данных?','Где остаётся допущение и кто его подтвердит?','Как показать, что результат выдерживает отрицательный пример?']},{explanation:units.slice(li*4,li*4+4).flatMap(u=>u.qa).map(([q,a])=>`${q} ${a}`).join(' '),transition:'Сохраняем конспект и отмечаем вопросы, требующие уточнения источников.'});
 c.lectures.push(l);
 registry.push({lectureId:l.id,title:l.title,semester:7,hours:null,slides:l.slides.length,questions:4,tasks:l.slides.filter(s=>s.task).length,visuals:l.slides.filter(s=>s.visual).length,contentVersion:version,source:'app/course.ts + app/course-data.ts (исходная версия)',data:'собрано',teacher:withTeacher?'собрано':'см. отдельный приватный комплект',pdf:'запланировано',checks:'запланировано',estimatedMinutes:withTeacher?Math.round(l.slides.reduce((sum,s)=>sum+teacher.notes[s.id].estimatedSeconds,0)/60):null});
 // Все старые ID: смысловые фрагменты сохранены либо заменены с явной причиной.
 const oldIds=['start','course-theme','main-literature','additional-literature','materials','why','case','route','start-model','outcomes','artifact-path','diagnostic',...Array.from({length:8},(_,i)=>['divider','definition','mechanism','case','decision','mistake','check'].map(k=>`c${i+1}-${k}`)).flat(),'practice-scenario','practice-artifact','practice-compare','practice-process','practice-schema','practice-discussion','practice-review','practice-reflection','test-multi','test-order','test-match','test-diagram','test-short','test-self','cheat','final','questions'];
 for(const id of oldIds){let target=l.slides.find(s=>s.id===`${l.id}-${id}`);let targets=target?[target.id]:[];const m=id.match(/^c(\d+)-(divider|check)$/);if(m){const q=Math.ceil(Number(m[1])/2);targets=l.slides.filter(s=>s.id.startsWith(`${l.id}-Q0${q}`)&&(m[2]==='check'?s.task:s.kind==='section')).map(s=>s.id);}if(!targets.length)targets=[`${l.id}-${id.startsWith('test')||id==='diagnostic'?'Q01-T01':id==='course-theme'?'start':id==='cheat'?'summary':'final'}`];mapping.push({lectureId:l.id,oldSlideId:id,newSlideIds:targets,change:target?'Сохранён смысл; данные адаптированы к общему макету и дополнены контекстом.':m?'Понятия сгруппированы попарно; старые повторные тесты заменены четырьмя типами вопроса.':'Повторная вводная/общая практика объединена с результатами и предметными разборами; открытые задания перенесены в обсуждение, неполные тесты заменены.'});}
}
// Объединяем повторные термины только при совпадении определения.
const gl=new Map();for(const g of c.glossary){const k=g.term+'|'+g.definition;if(gl.has(k))gl.get(k).slideIds.push(...g.slideIds);else gl.set(k,g);}c.glossary=[...gl.values()];
for(const dir of ['public','authoring','reports','private'])fs.mkdirSync(dir,{recursive:true});
const write=(p,x)=>fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n');
write('public/course.json',c);write('public/assessment.json',bank);write('authoring/questions.json',questionMap);write('reports/registry.json',registry);write('reports/migration-map.json',mapping);
if(withTeacher){write('private/teacher-source.json',teacherSource);write('private/teacher-pack.json',teacher);fs.writeFileSync('private/teacher.md',c.lectures.map(l=>`# ${l.title}\n\n`+l.slides.map(s=>{const n=teacher.notes[s.id];return `## ${s.id} · ${s.title}\n\n${n.script}\n\nПодготовка: ${n.preparation}\n\nКонспект: ${n.notebook}\n\n${n.questions}\n\n${n.answer}\n\nРасчёт: ${n.estimatedSeconds} с.\n`;}).join('\n')).join('\n'));write('private/preparation-cards.json',c.lectures.map((l,i)=>({lectureId:l.id,prerequisites:i?'Материал предшествующих тем; факты, решения и проверка.':'Различение документа, факта и предположения.',logic:units.slice(i*4,i*4+4).map(u=>u.title),questions:units.slice(i*4,i*4+4).flatMap(u=>u.qa),uncertainties:['РПД и официальные часы не предоставлены.','Вид аттестации и вариативная часть группы не указаны; статусы ГОСТ Р 59793-2021 и ГОСТ 34.201-2020 требуют подтверждения.'],estimatedMinutes:registry[i].estimatedMinutes})));
}
console.log(JSON.stringify({lectures:c.lectures.length,slides:c.lectures.map(l=>l.slides.length),tasks:Object.keys(bank.keys).length,notes:Object.keys(teacher.notes).length}));
